### PR TITLE
Jarvis 2.0

### PR DESCRIPTION
**Pull request by vipulraj01**
Added Desktop Notification 
Added Restart Function
Added Arthimatic Operation
Added Opening of all the application available on the system

### CODE REVIEW

**Comment by DrHacker3** [comment]
nice job I love the new startup

**Comment by vipulraj01** [comment]
> nice job I love the new startup

I can contribute more if you want to

**Comment by DrHacker3** [comment]
feel free too. I am working on voice version.

**Comment by vipulraj01** [comment]
i am trying to add some live weather and live time features in it

**Comment by DrHacker3** [comment]
try openweather for weather.

**Pull request merged**
